---
name: "Homebrew Release"
description: "A reusable action to publish a Homebrew formula to a tap."
author: "LizardByte"
inputs:
  local_repo_directory:
    description: 'The location of the local directory. If the default is not used, you must pass the entire path.'
    default: "homebrew"
    required: false
  git_email:
    description: 'The email to use for the commit.'
    required: true
  git_username:
    description: 'The username to use for the commit.'
    required: true
  target_repo:
    description: 'The target repository to publish to.'
    default: 'LizardByte/homebrew'
    required: false
  target_repo_branch:
    description: 'The target repository branch to publish to.'
    default: ''
    required: false
  token:
    description: 'Github Token.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout database
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.target_repo }}
        ref: ${{ inputs.target_repo_branch }}
        path: ${{ github.action_path }}/build
        persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of the personal token
        fetch-depth: 0  # otherwise, will fail to push refs to dest repo

    - name: Prepare Homebrew repo
      shell: bash
      run: |
        if [ "${{ inputs.local_repo_directory }}" == "homebrew" ]; then
          source_path="${{ github.workspace }}/${{ inputs.local_repo_directory }}"
        else
          source_path="${{ inputs.local_repo_directory }}"
        fi

        # copy local repo to target repo
        cp -f -r ${source_path}/. ${{ github.action_path }}/build/

    - name: GitHub Commit & Push
      uses: actions-js/push@v1.4
      with:
        author_email: ${{ inputs.git_email }}
        author_name: ${{ inputs.git_username }}
        branch: ${{ inputs.target_repo_branch }}  # commit to target branch
        directory: ${{ github.action_path }}/build  # use the build directory
        github_token: ${{ inputs.token }}
        message: "Update ${{ github.repository }} to ${{ github.sha }}"
